### ISSUE TITLE
Delete and add row buttons in the classic skin

### ISSUE THREAD

**Issue by ghost** [corbosman/message_highlight#6]
The message highlights setting buttons to delete and add a row only work in the larry skin, they do not work in the classic skin. The other settings work in both skins.

**Comment by Finside** [comment]
Thank you <b>shurshur</b>!

I confirm. It also helps with message_highlight Ver. 2.6 with Roundcube Webmail Ver. 1.1.2.
Both skins classic skin and larry are working good.
Also you may add translation for your language. I needed to add it for Russian.
