### ISSUE TITLE
Default rule from settings, very usefully for enterprice instalations

### ISSUE THREAD

**Issue by mckaygerhard** [corbosman/message_highlight#7]
in setting made a default rule for all users, so then , when loggin all users have a rule that macht such "warni9ng mails for alers"

obviously this will need a "confi8g.inc.php.dist" file and default settings... or maybe a default sql settings for users documented...

**Comment by mckaygerhard** [comment]
hi @corbosman if there's no people or way to work in that, how can i made to do and post a pull request to contribute?

i can made something but i need some directions!

**Comment by corbosman** [comment]
Ok, 4.2 support a config file. You can see the config file in the plugin, just rename it and add your settings.
